X = Manifold('DT:[(-62,-40,66,-36,-70,-48,76,-42,-64,38,-68,-50,54,72,-46,-24,52,16,-4,20,8,-26,-58,-12,60,34,32,-44,74,30),(80,22,6,-18,2,14,56,28,10),(78,)]')
X.dehn_fill((0,1),1)
Z = X.filled_triangulation()
Z.solution_type()
Z.volume()
Kverify = Z.copy()
Kverify.dehn_fill((0,1),1)
Kfill = Kverify.filled_triangulation()
Kfill.solution_type()
Kfill.identify()
Kfill.volume()
Z.dehn_fill((-27,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-26,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-25,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-24,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-23,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-22,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-21,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-20,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-19,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-18,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-17,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-16,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-15,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-14,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-13,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-12,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-11,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-10,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-9,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-8,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-7,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-6,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-5,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-4,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-3,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-2,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-1,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((0,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((1,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((2,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((3,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((4,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((5,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((6,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((7,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((8,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((9,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((10,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((11,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((12,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((13,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((14,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((15,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((16,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((17,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((18,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((19,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((20,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((21,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((22,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((23,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((24,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((25,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((26,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((27,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
