X = Manifold('DT:[(58,-112,-122,90,34,-74,38,-62,138,-8,-32,80,-52,126,-24,88,-100,12,-96,70,68,66,64,-18,6,84,-28,120,-108,-114,94,46,44,42,40,-14,98,-10,22,-86,54,-124,30,-78,-102,48,-136,72,-36,76,20,-50,118,130,-56,106,132,-60,-4,-128),(-92,104,26,-82,110,-2,116,140,16),(134,)]')
X.dehn_fill((0,1),1)
Z = X.filled_triangulation()
Z.solution_type()
Z.volume()
Kverify = Z.copy()
Kverify.dehn_fill((0,1),1)
Kfill = Kverify.filled_triangulation()
Kfill.solution_type()
Kfill.identify()
Kfill.volume()
Z.dehn_fill((-27,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-26,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-25,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-24,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-23,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-22,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-21,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-20,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-19,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-18,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-17,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-16,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-15,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-14,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-13,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-12,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-11,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-10,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-9,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-8,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-7,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-6,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-5,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-4,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-3,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-2,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-1,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((0,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((1,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((2,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((3,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((4,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((5,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((6,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((7,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((8,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((9,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((10,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((11,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((12,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((13,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((14,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((15,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((16,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((17,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((18,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((19,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((20,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((21,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((22,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((23,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((24,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((25,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((26,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((27,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
