X = Manifold('DT:[(90,-138,32,100,-42,-110,-84,150,-56,-124,66,134,-74,156,-68,-24,-46,-114,80,-154,20,64,132,76,-144,36,104,12,-86,148,-54,-122,-8,136,96,94,92,4,-118,50,-128,-60,-16,108,40,-28,72,70,30,-22,-44,-112,82,-152,18,62,130,-78,142,34,102,10,-88,146,-52,-120,-6,-98),(26,158,-48,116,-38,-106,14,58,126,-2),(140,)]')
X.dehn_fill((0,1),1)
Z = X.filled_triangulation()
Z.solution_type()
Z.volume()
Kverify = Z.copy()
Kverify.dehn_fill((0,1),1)
Kfill = Kverify.filled_triangulation()
Kfill.solution_type()
Kfill.identify()
Kfill.volume()
Z.dehn_fill((-27,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-26,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-25,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-24,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-23,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-22,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-21,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-20,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-19,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-18,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-17,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-16,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-15,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-14,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-13,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-12,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-11,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-10,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-9,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-8,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-7,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-6,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-5,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-4,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-3,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-2,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-1,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((0,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((1,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((2,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((3,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((4,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((5,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((6,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((7,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((8,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((9,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((10,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((11,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((12,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((13,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((14,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((15,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((16,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((17,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((18,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((19,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((20,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((21,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((22,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((23,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((24,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((25,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((26,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((27,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
