X = Manifold('DT:[(14,-66,54,28,-80,42,2,90,88,68,-36,-62,10,-92,-50,58,-46,84,-20,4,-96,24,72,-32,76,6,-102,30,-74,34,82,-12,98,-86,22,-60,48,-56,-8,94,-44,-70,38,18,16),(-52,78,-26,64,104,-40),(100,)]')
X.dehn_fill((0,1),1)
Z = X.filled_triangulation()
Z.solution_type()
Z.volume()
Kverify = Z.copy()
Kverify.dehn_fill((0,1),1)
Kfill = Kverify.filled_triangulation()
Kfill.solution_type()
Kfill.identify()
Kfill.volume()
Z.dehn_fill((-26,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-25,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-24,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-23,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-22,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-21,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-20,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-19,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-18,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-17,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-16,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-15,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-14,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-13,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-12,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-11,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-10,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-9,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-8,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-7,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-6,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-5,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-4,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-3,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-2,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((-1,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((0,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((1,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((2,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((3,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((4,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((5,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((6,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((7,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((8,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((9,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((10,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((11,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((12,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((13,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((14,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((15,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((16,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((17,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((18,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((19,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((20,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((21,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((22,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((23,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((24,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((25,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
Z.dehn_fill((26,1),0)
Knprime = Z.filled_triangulation()
Knprime.solution_type()
Knprime.volume()
Knprime.identify()
